x = 12
y = 10
print("A soma de", x,"+", y, "=", x+y)
print("A subtração de", x,"-", y, "=", x-y)
print("A multiplicação de", x,"x", y, "=", x*y)
print("A divisão de", x,"/", y, "=", x/y)
print("A divisão inteira", x,"//", y, "=", x//y)
print("A exponenciação de", x,"**", y, "=", x**y)
print("A potenciação de", x,"%", y, "=", x%y)
